repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.28.0
  hooks:
  - id: gitleaks
- repo: https://github.com/golangci/golangci-lint
  rev: v2.3.1
  hooks:
  - id: golangci-lint-config-verify
  - id: golangci-lint-full
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
ci:
  # https://pre-commit.ci/#configuration
  skip:
    - golangci-lint-config-verify
    - golangci-lint-full
