name: "Commit linting"

on: [push, pull_request]

jobs:
  commit-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        # Checkout the entire pull request branch
        repository: ${{github.event.pull_request.head.repo.full_name}}
        ref: ${{github.event.pull_request.head.ref}}
        fetch-depth: ${{github.event.pull_request.commits}}
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        ref: main
        fetch-depth: 1
    - name: Set up Python 3.13
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitlint
    - name: Analysing the commits
      run: |
        .github/workflows/run-gitlint.sh
